version: '3.9'

services:

  mosquitto:
    image: eclipse-mosquitto
    hostname: mosquitto
    container_name: mosquitto
    expose:
      - "1881"
      - "9001"
      - "1883"
    ports:
      - "1881:1881"
      - "9001:9001"
      - "1883:1883"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf

  proxy:
    depends_on:
      - mosquitto
    build: ./proxy
    links:
      - "mosquitto:mosquitto"