version: '3.8'

services:

  mosquitto:
    image: eclipse-mosquitto:latest
    restart: always
    ports:
      - "1881:1881"
      - "9001:9001"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - emeter

  influxdb:
    image: influxdb:1.8.10
    restart: always
    ports: 
     - "8086:8086"
    networks:
     - emeter
    volumes:
     - influxdb-data:/var/lib/influxdb

#  proxy:
#    depends_on:
#      - mosquitto
#    build: ./proxy
#    environment:
#      - MQTT_HOST=mosquitto
#    networks:
#     - emeter

  telegraf:
    image: telegraf
    restart: always
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - mosquitto
      - influxdb
    networks:
     - emeter
  
  grafana:
    image: grafana/grafana
    restart: always
    ports:
      - "3000:3000"
    networks:
     - emeter
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - influxdb

networks:
  emeter:

volumes:
  influxdb-data:
  grafana-data: